/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from '../../app/planner-app.component';
const styles_PlannerAppComponent:any[] = ([] as any[]);
export const RenderType_PlannerAppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PlannerAppComponent,data:{}});
export function View_PlannerAppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),5,'div',[['class','app-root']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),i0.ɵdid(278528,(null as any),0,i1.NgClass,
      [i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,
          'klass'],ngClass:[1,'ngClass']},(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' Projects '])),(_l()(),i0.ɵted((null as any),['\n        ']))],
      (_ck,_v) => {
        const currVal_0:any = 'app-root';
        const currVal_1:any = 'loaded';
        _ck(_v,2,0,currVal_0,currVal_1);
      },(null as any));
}
export function View_PlannerAppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'planner-app',
      ([] as any[]),(null as any),(null as any),(null as any),View_PlannerAppComponent_0,
      RenderType_PlannerAppComponent)),i0.ɵdid(49152,(null as any),0,i2.PlannerAppComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PlannerAppComponentNgFactory:i0.ComponentFactory<i2.PlannerAppComponent> = i0.ɵccf('planner-app',
    i2.PlannerAppComponent,View_PlannerAppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovUHJvamVjdHMvbmdQbGFubmVyL3NyYy9uZ1BsYW5uZXIvd3d3cm9vdC9hcHAvcGxhbm5lci1hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1Byb2plY3RzL25nUGxhbm5lci9zcmMvbmdQbGFubmVyL3d3d3Jvb3QvYXBwL3BsYW5uZXItYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L1Byb2plY3RzL25nUGxhbm5lci9zcmMvbmdQbGFubmVyL3d3d3Jvb3QvYXBwL3BsYW5uZXItYXBwLmNvbXBvbmVudC50cy5QbGFubmVyQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Qcm9qZWN0cy9uZ1BsYW5uZXIvc3JjL25nUGxhbm5lci93d3dyb290L2FwcC9wbGFubmVyLWFwcC5jb21wb25lbnQudHMuUGxhbm5lckFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYXBwLXJvb3RcIiBbbmdDbGFzc109XCInbG9hZGVkJ1wiPlxuICAgICAgICAgICAgPGgxPiBQcm9qZWN0cyA8L2gxPlxuICAgICAgICA8L2Rpdj4iLCI8cGxhbm5lci1hcHA+PC9wbGFubmVyLWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLG1EQUFBO01BQUE7VUFBQSwrQ0FBMkM7TUFBQSxxQkFDdkM7TUFBQSx3RUFBSTthQUFBLGdDQUFlOztRQURsQjtRQUFpQjtRQUF0QixXQUFLLFVBQWlCLFNBQXRCOzs7O29CQ0RSO01BQUE7b0NBQUEsVUFBQTtNQUFBOzs7In0=
